name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: docker build
        run: |
          IMAGE=4pdosc/prpc:0.0.0
          docker build -t 4pdosc/prpc-base:latest -f docker/Dockerfile.base .
          docker build -t ${IMAGE} -f docker/Dockerfile .