name: release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build and push
        run: |
          IMAGE=4pdosc/prpc:${BRANCH_NAME:1}
          docker build -t 4pdosc/prpc-base:latest -f docker/Dockerfile.base .
          docker build -t ${IMAGE} -f docker/Dockerfile .
          docker push ${IMAGE}

